### ISSUE TITLE
Error on all cloud recognitions 

### ISSUE THREAD

**Issue by GeoffSeloana** [Tazaf/IonicitudeDemoApp#2]
I just ran the sample app and everything works well except the following worlds

2_CloudRecognition_2_ContinuousRecognitionVsOn-Click
2_CloudRecognition_3_UsingMetainformationInTheResponse

getting the following error 

![image](https://cloud.githubusercontent.com/assets/8654757/16901849/28f3702c-4c4f-11e6-8672-a2aae5e1fc15.png)

I have not done anything yet on the code.

**Comment by Tazaf** [comment]
Hi !
I'll look into that problem soon and will come back to you.
(I didn't test all the worlds after making the demo app)

**Comment by GeoffSeloana** [comment]
Greetings sir... have you had some time to check the error

**Comment by Tazaf** [comment]
Hi !

My deepest apologies, but no, I haven't had quite the time to look into the matter recently
(Too. Much. Work :weary:)

I'll try to spare some time this afternoon for that, though.

**Comment by GeoffSeloana** [comment]
Okay thank you so much. Much appreciated

**Comment by Tazaf** [comment]
Wel... I've just tried the demo app on my side (by following the installation procedure from scratch) and everything's working nicely for the two worlds you've mentionned.
They launch without any issue and works as expected.

When did the error message occur ? Right when you launched the world or when you tried to scan the pictures ?

**Comment by GeoffSeloana** [comment]
I have just tried it now. It happens when i click on the button. and in the other world it happens without clicking

**Comment by Tazaf** [comment]
Which button ? The one that says **"Scan"** in the 2_CloudRecognition_1_BasicRecognitionOn-Click world ?

Well, I don't know what to say. I can't reproduce the issue on my side, so it's difficult to debug.
What happen when you develop the Uncaught Syntax Error on the console ? On the screenshot you provided, they're all collapsed.

I could only advise you to dig into the code of the first world (since you can manually trigger the scan), and try and pinpoint what line exactly is causing the error.

In anyway, I can safely say that the problem is not related to Ionicitude, since this world does not rely on the module to work (except for the launching, but this step seems to be OK).

**Comment by GeoffSeloana** [comment]
![image](https://cloud.githubusercontent.com/assets/8654757/17588415/fb76e988-5fce-11e6-83c3-7d2e323a97c4.png)

So this happens when i click on the "Scan" button. And i just downloaded this code from the repo. haven't changed anything at all.

Would you mind sending me the one you tried, the one that works.

**Comment by Tazaf** [comment]
Well...
I just didn't do anything other that cloning the code on the repo, too 😕 

Do you have any more information from the console (like by clicking the gray arrow beside the error message) ?

Quite frankly, I don't understand what could cause the issue. And since I can't reproduce it on my side, it's really hard to dig into it.

**Comment by GeoffSeloana** [comment]
So nothing shows up when i click on the down arrow. but when i click on the silver link on the side then this shows

setTimeout(function(){AR.om.getObjectForID(1).onRecognitionError(400, "{"code":400,"reason":"HEADER_PROPERTY_INVALID","message":"One or more header properties are invalid.","cause":[{"item":"X-Horizontal-FOV","value":"0"}],"moreInfo":"http://www.wikitude.com/developer/documentation/cloudrecognition"}");},0)

**Comment by Tazaf** [comment]
Hum... From this message, I assume that there is some kind of header error when your device try to access the API. But I don't know what's causing it.

Anyway, with the code that you copied on your last message, we can see that it's some code that tries to execute this onErrorRecognition callback: 

``` javascript
onRecognitionError: function onRecognitionError(errorCode, errorMessage) {
    alert("error code: " + errorCode + " error message: " + JSON.stringify(errorMessage));
},
```

Except it seems to pass a value for errorMessage that's all messed up with the quotation mark, as you can see (I've trimmed the message up to the first quotation mark):

``` javascript
"{"code":400,"reason":"HEADER_PROPERTY_INVALID","message":"One or more header properties are invalid.","cause":[{"item":"X-Horizontal-FOV","value":"0"}],"moreInfo":"http://www.wikitude.com/developer/documentation/cloudrecognition"}");},0)
```

I think that it's what causing the Uncaught Syntax Error.
But it's code that I have no access to.

I think you should discuss this issue directly with the folks at Wikitude, sorry.

**Comment by GeoffSeloana** [comment]
Please replace the wikitudesdk.aar (for Android) or WikitudeSDK.framework (for iOS) in your existing Cordova project with the latest from wikitude download section. [Android](http://wikitude-web-hosting.s3.amazonaws.com/sdk/developer-channel-releases/Android/WikitudeSDK_Android_5-2-0_2016-07-26_10-16-46.zip),[IOS](http://wikitude-web-hosting.s3.amazonaws.com/sdk/developer-channel-releases/iOS/WikitudeSDK_iOS_5-2-0_2016-07-26_09-57-18.zip)
This worked for me :-)

**Comment by Tazaf** [comment]
I'm glad you found a solution !
But I can't replace the sdk, since it's not present in the project: it's downloaded when you use the `ionic state restore` command.
I'll update the doc and insert your advice, though :wink:
