### ISSUE TITLE
Ionic 3

### ISSUE THREAD

**Issue by sophianachiba** [Tazaf/IonicitudeDemoApp#6]
hello,

I'm not sure if you are actively working on your project but I tried to use your code and the documentation is no longer valid b/c ionic has evolved.
Typically things like "ionic state restore" no longer work.
Anyway, I'm still trying to get it to work, have you tried it with ionic 3?

**Comment by Tazaf** [comment]
Hi !

Looks like you opened two identical issues about this. I'm closing this one and leaving the other one open 😉
